include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - always_put_control_body_on_new_line
    - avoid_escaping_inner_quotes
    - avoid_relative_lib_imports
    - avoid_multiple_declarations_per_line
    - avoid_returning_null_for_future
    - avoid_web_libraries_in_flutter
    - avoid_void_async
    - close_sinks
    - empty_statements
    - file_names
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - use_named_constants
    - use_string_buffers
    - control_flow_in_finally
    - no_duplicate_case_values
    - throw_in_finally
    - test_types_in_equals
    - unnecessary_statements
    - unrelated_type_equality_checks
    - always_declare_return_types
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
